// Generates supabase/seed.sql from the original hard-coded content in
// supabase/seed-data/*.mjs. The app itself never imports those files — after
// seeding, everything is edited from the dashboard.
//
//   node scripts/generate-seed.mjs
//
// Every statement is idempotent (ON CONFLICT DO NOTHING / insert-if-empty), so
// re-running the seed never overwrites content edited in the dashboard.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dict, navItems } from '../supabase/seed-data/i18n.mjs';
import { site } from '../supabase/seed-data/site.mjs';
import { products, brandLogos, SHAPES } from '../supabase/seed-data/products.mjs';
import { brands, projects, certifications, timeline, missionGoals, documents } from '../supabase/seed-data/company.mjs';
import { articles } from '../supabase/seed-data/blog.mjs';

// ---------------------------------------------------------------- SQL helpers
const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const json = (v) => `${q(JSON.stringify(v))}::jsonb`;
const arr = (list = []) => (list.length ? `array[${list.map(q).join(', ')}]::text[]` : `'{}'::text[]`);
const bool = (b) => (b ? 'true' : 'false');
const loc = (v) => (v && typeof v === 'object' && 'ar' in v ? v : { ar: v ?? '', en: v ?? '' });

const out = [];
const emit = (s = '') => out.push(s);
const both = (fn) => ({ ar: fn('ar'), en: fn('en') });

emit('-- =============================================================================');
emit('-- TOP POWER — default CMS content (generated by scripts/generate-seed.mjs)');
emit('-- Safe to re-run: existing rows are never overwritten.');
emit('-- =============================================================================');
emit('begin;');
emit();

// ------------------------------------------------------------- site settings
const greeting = { ar: 'مرحباً توب باور، أريد الاستفسار عن', en: 'Hello TOP POWER, I would like to ask about' };
const links = navItems.map((n) => ({ label_ar: dict.ar.nav[n.key], label_en: dict.en.nav[n.key], href: n.href, visible: true }));
const mapEmbed = `https://maps.google.com/maps?q=${encodeURIComponent(site.mapQuery)}&z=16&output=embed`;

emit('-- Site settings (singleton)');
emit(`insert into public.site_settings (
  id, site_name_ar, site_name_en, logo_text, tagline_ar, tagline_en, legal_name_ar, legal_name_en,
  logo_url, logo_full_url, favicon_url, og_image_url, color_primary, color_secondary, color_accent,
  phones, call_number, whatsapp_number, whatsapp_greeting_ar, whatsapp_greeting_en, email,
  address_ar, address_en, working_hours_ar, working_hours_en, map_embed_url,
  facebook_url, instagram_url, tiktok_url, nav_links, footer_links,
  importers_number, tax_card_number, vat_registered, certifications_strip,
  site_url, meta_title_ar, meta_title_en, meta_description_ar, meta_description_en
) values (
  1, ${q(site.name.ar)}, ${q(site.name.en)}, 'TOP POWER', ${q(site.tagline.ar)}, ${q(site.tagline.en)}, ${q(site.legalName.ar)}, ${q(site.legalName.en)},
  '/images/logo.jpg', '/images/logo-full.jpg', '/images/logo.jpg', '/images/logo-full.jpg', '#153726', '#215733', '#CDB074',
  ${arr(site.phones)}, ${q(site.phones[0])}, ${q(site.whatsapp)}, ${q(greeting.ar)}, ${q(greeting.en)}, ${q(site.email)},
  ${q(site.address.ar)}, ${q(site.address.en)}, ${q(dict.ar.contact.hoursValue)}, ${q(dict.en.contact.hoursValue)}, ${q(mapEmbed)},
  ${q(site.social.facebook)}, ${q(site.social.instagram)}, ${q(site.social.tiktok)}, ${json(links)}, ${json(links)},
  ${q(site.registrations.importers)}, ${q(site.registrations.taxCard)}, true, 'UL · FM · LPCB · VdS · NFPA',
  'https://example.com', 'توب باور – مستلزمات هندسية MEP', 'TOP POWER – MEP Engineering Supplies',
  'توب باور – مورّد أنظمة الحماية من الحريق ومستلزمات MEP المعتمدة UL / FM / LPCB / VdS في مصر والسعودية.',
  'TOP POWER supplies UL / FM / LPCB / VdS approved fire protection systems and MEP supplies in Egypt & KSA.'
) on conflict (id) do nothing;`);
emit();

// -------------------------------------------------------------- translations
// Page-specific copy (hero, home, about, prefooter, contact form) moves into
// section content; everything else is static UI text.
const SECTION_OWNED = new Set(['hero', 'home', 'about', 'prefooter']);
const MOVED_KEYS = new Set(['contact.formTitle', 'contact.formDesc', 'contact.infoTitle', 'contact.sent', 'contact.hoursValue']);
const ROOT_TO_COMMON = { langSwitch: 'common.langSwitch', langLabel: 'common.langLabel', menu: 'common.menu', close: 'common.close' };

const flat = {};
const put = (key, lang, value) => ((flat[key] ||= { ar: '', en: '' })[lang] = value);
for (const lang of ['ar', 'en']) {
  for (const [ns, val] of Object.entries(dict[lang])) {
    if (SECTION_OWNED.has(ns)) continue;
    if (typeof val === 'string') put(ROOT_TO_COMMON[ns] || `common.${ns}`, lang, val);
    else for (const [k, v] of Object.entries(val)) if (!MOVED_KEYS.has(`${ns}.${k}`)) put(`${ns}.${k}`, lang, v);
  }
}
// Strings that used to be inline in components.
const extra = {
  'common.photoSoon': { ar: 'الصورة قريباً', en: 'Photo coming soon' },
  'common.scroll': { ar: 'مرر للأسفل', en: 'Scroll down' },
  'common.prev': { ar: 'السابق', en: 'Previous' },
  'common.next': { ar: 'التالي', en: 'Next' },
  'common.breadcrumb': { ar: 'مسار التنقل', en: 'Breadcrumb' },
  'common.empty': { ar: 'لا يوجد محتوى بعد.', en: 'Nothing here yet.' },
  'footer.credit': { ar: 'تصميم وتطوير', en: 'Designed & developed by' },
  'blog.empty': { ar: 'لا توجد مقالات منشورة بعد.', en: 'No published articles yet.' },
};
Object.assign(flat, extra);
for (const [k, v] of Object.entries(SHAPES)) flat[`shapes.${k}`] = v;

emit('-- UI translations');
emit('insert into public.translations (key, value_ar, value_en) values');
emit(
  Object.entries(flat)
    .map(([k, v]) => `  (${q(k)}, ${q(v.ar)}, ${q(v.en)})`)
    .join(',\n') + '\non conflict (key) do nothing;',
);
emit();

// -------------------------------------------------------------------- pages
const meta = {
  home: { path: '/', title: { ar: 'الرئيسية', en: 'Home' }, metaTitle: null, desc: null },
  about_us: {
    path: '/about',
    title: { ar: 'من نحن', en: 'About Us' },
    desc: { ar: 'أكثر من 20 عاماً في توريد أنظمة الحماية من الحريق المعتمدة في مصر والسعودية.', en: '20+ years supplying approved fire protection systems in Egypt and KSA.' },
  },
  market: {
    path: '/products',
    title: { ar: 'المنتجات والكتالوج', en: 'Products & Catalog' },
    desc: { ar: 'مواسير سيملس، وصلات، محابس، رشاشات وصناديق حريق معتمدة UL / FM.', en: 'Seamless pipes, fittings, valves, sprinklers and fire cabinets – UL / FM approved.' },
  },
  blogs: {
    path: '/blog',
    title: { ar: 'المدونة', en: 'Blog' },
    desc: { ar: 'مقالات فنية عن أنظمة مكافحة الحريق والاعتمادات واختيار المواد.', en: 'Technical articles on fire protection systems, approvals and material selection.' },
  },
  contact_us: {
    path: '/contact',
    title: { ar: 'اتصل بنا', en: 'Contact Us' },
    desc: { ar: 'تواصل مع توب باور – القاهرة، الأزبكية، 23 شارع عماد الدين.', en: 'Contact TOP POWER – 23 Emad El-Din St., Azbakeya, Cairo.' },
  },
};

emit('-- Pages');
emit('insert into public.pages (slug, path, title_ar, title_en, meta_title_ar, meta_title_en, meta_description_ar, meta_description_en, sort_order) values');
emit(
  Object.entries(meta)
    .map(([slug, m], i) => {
      const t = slug === 'home' ? { ar: null, en: null } : m.title;
      return `  (${q(slug)}, ${q(m.path)}, ${q(m.title.ar)}, ${q(m.title.en)}, ${q(t.ar)}, ${q(t.en)}, ${q(m.desc?.ar)}, ${q(m.desc?.en)}, ${i})`;
    })
    .join(',\n') + '\non conflict (slug) do nothing;',
);
emit();

// ------------------------------------------------------------------ sections
const T = (lang) => dict[lang];
const hero = (page, image, badges = []) =>
  both((l) => ({
    title: T(l).hero[page].title[0],
    title_highlight: T(l).hero[page].title[1],
    description: T(l).hero[page].desc,
    image,
    cta_primary_label: T(l).cta.contact,
    cta_primary_href: '/contact',
    cta_secondary_label: T(l).cta.explore,
    cta_secondary_href: '/products',
    badges: badges.map((label) => ({ label })),
  }));
const cta = both((l) => ({ title: T(l).prefooter.title, description: T(l).prefooter.desc, whatsapp_label: T(l).cta.whatsapp, call_label: T(l).cta.call }));
const heading = (eb, ti) => both((l) => ({ eyebrow: eb(l), title: ti(l), description: '' }));
const pickL = (v, l) => loc(v)[l];

const sections = {
  home: [
    ['hero_section', 'hero', 'Hero Section', hero('home', '/images/cover.jpg', ['UL Listed', 'FM Approved', 'NFPA'])],
    [
      'about_summary',
      'about_summary',
      'About Summary',
      both((l) => ({
        counter_value: 15,
        counter_suffix: '+',
        counter_label: T(l).home.stats[0].label,
        title_prefix: '15+',
        title: T(l).home.expTitle,
        description: T(l).home.expDesc,
        ring_text: 'FIRE SAFETY · MEP SOLUTIONS · UL · FM · NFPA · SINCE 20 YEARS ·',
        stats: T(l).home.stats,
      })),
    ],
    ['bento_grid', 'heading', 'Product Bento Grid', heading((l) => T(l).home.productsEyebrow, (l) => T(l).home.productsTitle)],
    ['partners_marquee', 'heading', 'Partners Marquee', heading((l) => T(l).home.brandsEyebrow, (l) => T(l).home.brandsTitle)],
    [
      'key_projects',
      'key_projects',
      'Key Projects',
      both((l) => ({ eyebrow: T(l).home.projectsEyebrow, title: T(l).home.projectsTitle, hint: T(l).home.projectsHint })),
    ],
    ['pre_footer_cta', 'cta', 'Pre-footer CTA', cta],
  ],
  about_us: [
    ['hero_section', 'hero', 'Hero Section', hero('about', '/images/about-team.jpg')],
    [
      'company_history',
      'history',
      'Company History',
      both((l) => ({
        eyebrow: T(l).about.storyEyebrow,
        title: T(l).about.storyTitle,
        image: '/images/about-team.jpg',
        badge_value: '20+',
        badge_line1: l === 'ar' ? 'عاماً من' : 'years of',
        badge_line2: l === 'ar' ? 'الخبرة' : 'experience',
        timeline: timeline.map((s) => ({ year: pickL(s.year, l), title: pickL(s.title, l), text: pickL(s.text, l) })),
      })),
    ],
    [
      'mission_vision',
      'mission_vision',
      'Mission & Vision',
      both((l) => ({
        eyebrow: T(l).about.mgEyebrow,
        title: T(l).about.mgTitle,
        mission_title: T(l).about.mission,
        goals_title: T(l).about.goals,
        mission: missionGoals.mission.map((m) => ({ text: m[l] })),
        goals: missionGoals.goals.map((m) => ({ text: m[l] })),
      })),
    ],
    [
      'certifications',
      'certifications',
      'Certifications Badges',
      both((l) => ({
        eyebrow: T(l).about.certEyebrow,
        title: T(l).about.certTitle,
        items: certifications.map((c) => ({ code: c.code, name: c.name[l], desc: c.desc[l] })),
      })),
    ],
    [
      'legal_docs',
      'legal_docs',
      'Legal Documents',
      both((l) => ({
        eyebrow: T(l).about.docsEyebrow,
        title: T(l).about.docsTitle,
        description: T(l).about.docsDesc,
        zoom_hint: T(l).about.zoomHint,
        download_label: l === 'ar' ? 'تحميل المستند' : 'Download document',
      })),
    ],
    ['pre_footer_cta', 'cta', 'Pre-footer CTA', cta],
  ],
  market: [
    ['hero_section', 'hero', 'Hero Section', hero('products', '/images/brochure/mech-grooved.jpg')],
    ['pre_footer_cta', 'cta', 'Pre-footer CTA', cta],
  ],
  blogs: [
    ['hero_section', 'hero', 'Hero Section', hero('blog', '/images/brochure/mech-pipe.jpg')],
    ['blog_grid', 'heading', 'Articles Grid Heading', heading((l) => T(l).nav.blog, (l) => T(l).blog.latest)],
    ['pre_footer_cta', 'cta', 'Pre-footer CTA', cta],
  ],
  contact_us: [
    ['hero_section', 'hero', 'Hero Section', hero('contact', '/images/brochure/mech-valves.jpg')],
    [
      'contact_form',
      'contact_form',
      'Contact Form',
      both((l) => ({
        form_title: T(l).contact.formTitle,
        form_description: T(l).contact.formDesc,
        info_title: T(l).contact.infoTitle,
        success_message: T(l).contact.sent,
        error_message: l === 'ar' ? 'تعذر الإرسال، حاول مرة أخرى أو تواصل عبر واتساب.' : 'Sending failed. Please try again or reach us on WhatsApp.',
      })),
    ],
    ['pre_footer_cta', 'cta', 'Pre-footer CTA', cta],
  ],
};

emit('-- Sections + bilingual content');
for (const [page, list] of Object.entries(sections)) {
  list.forEach(([key, type, label, content], i) => {
    emit(
      `insert into public.sections (page_id, key, type, label, sort_order) select id, ${q(key)}, ${q(type)}, ${q(label)}, ${i} from public.pages where slug = ${q(page)} on conflict (page_id, key) do nothing;`,
    );
    emit(
      `insert into public.section_content (section_id, content_ar, content_en) select s.id, ${json(content.ar)}, ${json(content.en)} from public.sections s join public.pages p on p.id = s.page_id where p.slug = ${q(page)} and s.key = ${q(key)} on conflict (section_id) do nothing;`,
    );
  });
}
emit();

// --------------------------------------------------------- product catalog
const specs = (list = []) => list.map((s) => ({ label_ar: s.k.ar, label_en: s.k.en, value_ar: s.v.ar, value_en: s.v.en }));

emit('-- Product categories');
products.forEach((c, i) => {
  const b = c.brands.map((x) => loc(x)).map((x) => ({ name_ar: x.ar, name_en: x.en }));
  emit(`insert into public.product_categories (
  slug, icon, name_ar, name_en, short_ar, short_en, description_ar, description_en, cover_image, certs, standards,
  sizes_label_ar, sizes_label_en, pressure_label_ar, pressure_label_en, brands, specs,
  items_ar, items_en, applications_ar, applications_en, brochure, sort_order
) values (
  ${q(c.id)}, ${q(c.icon)}, ${q(c.name.ar)}, ${q(c.name.en)}, ${q(c.short.ar)}, ${q(c.short.en)}, ${q(c.description.ar)}, ${q(c.description.en)}, ${q(c.image)}, ${arr(c.certs)}, ${q(c.standards)},
  ${q(c.sizes.ar)}, ${q(c.sizes.en)}, ${q(c.pressure.ar)}, ${q(c.pressure.en)}, ${json(b)}, ${json(specs(c.specs))},
  ${arr(c.items.ar)}, ${arr(c.items.en)}, ${arr(c.applications.ar)}, ${arr(c.applications.en)}, ${arr(c.brochure)}, ${i}
) on conflict (slug) do nothing;`);
});
emit();

emit('-- Products (sub-types)');
products.forEach((c) => {
  c.groups.forEach((g, i) => {
    const pressure = loc(g.pressure);
    const brandRows = g.brands.map((b) => {
      const name = loc(b.name);
      return {
        name_ar: name.ar,
        name_en: name.en,
        logo: typeof b.name === 'string' ? brandLogos[b.name] || null : null,
        image: b.image || null,
        desc_ar: b.desc?.ar || '',
        desc_en: b.desc?.en || '',
        datasheet: b.datasheet || null,
        is_primary: !!b.primary,
      };
    });
    emit(`insert into public.products (
  category_id, slug, icon, name_ar, name_en, description_ar, description_en, cover_image, sizes,
  pressure_ar, pressure_en, standard, specs, shapes, brands, sort_order
) select id, ${q(g.id)}, ${q(g.icon)}, ${q(g.name.ar)}, ${q(g.name.en)}, ${q(g.desc.ar)}, ${q(g.desc.en)}, ${q(g.image)}, ${arr(g.sizes)},
  ${q(pressure.ar)}, ${q(pressure.en)}, ${q(g.standard)}, ${json(specs(g.specs))}, ${json(g.shapes || [])}, ${json(brandRows)}, ${i}
from public.product_categories where slug = ${q(c.id)}
on conflict (category_id, slug) do nothing;`);
  });
});
emit();

// --------------------------------------------------------------------- blogs
const toMarkdown = (blocks) =>
  blocks
    .map((b) => {
      if (b.h) return `### ${b.h}`;
      if (b.q) return `> ${b.q}`;
      if (b.ul) return b.ul.map((li) => `- ${li}`).join('\n');
      return b.p;
    })
    .join('\n\n');

emit('-- Blog articles');
articles.forEach((a) => {
  emit(`insert into public.blogs (
  slug, title_ar, title_en, excerpt_ar, excerpt_en, body_ar, body_en, category_ar, category_en,
  featured_image, display, status, published_at, read_time
) values (
  ${q(a.id)}, ${q(a.title.ar)}, ${q(a.title.en)}, ${q(a.excerpt.ar)}, ${q(a.excerpt.en)}, ${q(toMarkdown(a.body.ar))}, ${q(toMarkdown(a.body.en))}, ${q(a.category.ar)}, ${q(a.category.en)},
  ${q(a.image)}, ${q(a.featured ? 'hero' : 'grid')}, 'published', ${q(a.date)}, ${a.readTime}
) on conflict (slug) do nothing;`);
});
emit();

// ----------------------------------------------- documents, partners, projects
const DOC_TYPES = { tax: 'tax_card', commercial: 'commercial_register', vat: 'vat', importers: 'importers_card' };

emit('-- Company documents (only when the table is empty)');
emit('insert into public.company_documents (doc_type, title_ar, title_en, description_ar, description_en, image_url, sort_order)');
emit('select * from (values');
emit(documents.map((d, i) => `  (${q(DOC_TYPES[d.id] || 'other')}, ${q(d.title.ar)}, ${q(d.title.en)}, ${q(d.desc.ar)}, ${q(d.desc.en)}, ${q(d.image)}, ${i})`).join(',\n'));
emit(') v where not exists (select 1 from public.company_documents);');
emit();

emit('-- Partners & projects (only when the table is empty)');
const pp = [
  ...brands.map((b, i) => `  ('partner', ${q(b.name)}, ${q(b.name)}, null, null, null, null, ${q(b.logo)}, ${i})`),
  ...projects.map(
    (p, i) =>
      `  ('project', ${q(p.name.ar)}, ${q(p.name.en)}, ${q(p.place.ar)}, ${q(p.place.en)}, ${q(p.type.ar)}, ${q(p.type.en)}, ${q(p.image)}, ${i})`,
  ),
];
emit('insert into public.partners_and_projects (kind, title_ar, title_en, location_ar, location_en, category_ar, category_en, image_url, sort_order)');
emit('select * from (values');
emit(pp.join(',\n'));
emit(') v where not exists (select 1 from public.partners_and_projects);');
emit();

emit('commit;');
emit();

const target = fileURLToPath(new URL('../supabase/seed.sql', import.meta.url));
writeFileSync(target, out.join('\n'), 'utf8');
console.log(`Wrote ${target} (${out.length} lines)`);
