import 'server-only';
import { headers } from 'next/headers';

/** Default link-preview image (1200×630), generated by scripts/og-image.cjs from the logo. */
export const DEFAULT_OG_IMAGE = '/images/og-image.jpg';

/** Open Graph image entry; the default image carries its size so previews render at full width. */
export function ogImage(url, alt) {
  const src = url || DEFAULT_OG_IMAGE;
  return src === DEFAULT_OG_IMAGE ? { url: src, width: 1200, height: 630, alt } : { url: src, alt };
}

/**
 * Absolute origin used to turn relative image paths into full URLs (WhatsApp,
 * Facebook and X ignore relative og:image values). Uses the "Public site URL"
 * setting when it is a real domain, otherwise the host the request came in on,
 * so previews work on any domain the site is deployed to.
 */
export async function siteOrigin(configured) {
  try {
    const url = new URL(configured);
    if (!/(^|\.)example\.com$/i.test(url.hostname)) return url;
  } catch {
    // not set or not a URL — fall back to the request host
  }
  const h = await headers();
  const host = (h.get('x-forwarded-host') || h.get('host') || '').split(',')[0].trim();
  if (!host) return undefined;
  const proto = (h.get('x-forwarded-proto') || '').split(',')[0].trim() || (/^(localhost|127\.)/.test(host) ? 'http' : 'https');
  return new URL(`${proto}://${host}`);
}

/** Shared Open Graph + Twitter card fields. */
export function socialMeta({ title, description, image, siteName, lang }) {
  return {
    openGraph: {
      type: 'website',
      siteName,
      title,
      description,
      locale: lang === 'en' ? 'en_US' : 'ar_EG',
      images: [image],
    },
    twitter: { card: 'summary_large_image', title, description, images: [image.url] },
  };
}
